-- Read-only inventory for the production students security review.
select jsonb_build_object(
  'project_ref', 'hgdqarcdfycdesavwrvq',
  'rls_enabled', (select relrowsecurity from pg_class where oid = 'public.students'::regclass),
  'policies', (select coalesce(jsonb_agg(jsonb_build_object('name', policyname, 'command', cmd, 'roles', roles, 'permissive', permissive, 'using', qual, 'check', with_check) order by policyname), '[]'::jsonb) from pg_policies where schemaname='public' and tablename='students'),
  'table_grants', (select coalesce(jsonb_agg(jsonb_build_object('role', grantee, 'privilege', privilege_type) order by grantee, privilege_type), '[]'::jsonb) from information_schema.role_table_grants where table_schema='public' and table_name='students' and grantee in ('anon','authenticated','service_role','PUBLIC')),
  'columns', (select coalesce(jsonb_agg(jsonb_build_object('column', c.column_name, 'type', c.data_type, 'nullable', c.is_nullable, 'default', c.column_default, 'anon_select', has_column_privilege('anon','public.students',c.column_name,'SELECT'), 'auth_select', has_column_privilege('authenticated','public.students',c.column_name,'SELECT'), 'auth_insert', has_column_privilege('authenticated','public.students',c.column_name,'INSERT'), 'auth_update', has_column_privilege('authenticated','public.students',c.column_name,'UPDATE'), 'service_update', has_column_privilege('service_role','public.students',c.column_name,'UPDATE')) order by c.ordinal_position), '[]'::jsonb) from information_schema.columns c where c.table_schema='public' and c.table_name='students'),
  'column_grants', (select coalesce(jsonb_agg(jsonb_build_object('role', grantee, 'column', column_name, 'privilege', privilege_type) order by grantee, column_name, privilege_type), '[]'::jsonb) from information_schema.column_privileges where table_schema='public' and table_name='students' and grantee in ('anon','authenticated','service_role','PUBLIC')),
  'triggers', (select coalesce(jsonb_agg(jsonb_build_object('name', trigger_name, 'event', event_manipulation, 'timing', action_timing, 'statement', action_statement) order by trigger_name), '[]'::jsonb) from information_schema.triggers where event_object_schema='public' and event_object_table='students'),
  'admin_roles', (select coalesce(jsonb_agg(jsonb_build_object('level',admin_level,'status',status,'count',n) order by admin_level,status), '[]'::jsonb) from (select admin_level,status,count(*) n from public.admins group by admin_level,status) a)
) as students_security_inventory;
