import nodemailer from 'nodemailer';
import QRCode from 'qrcode';
import type { StudentRecord } from './types.js';

export interface QrMail {
  to: string;
  subject: string;
  html: string;
  text: string;
  attachments: { filename: string; content: Buffer | string; contentType: string }[];
}

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char] || char);
}

export async function buildQrMail(student: StudentRecord): Promise<QrMail> {
  const payload = `student_uuid:${student.student_id.toLowerCase()}`;
  const png = await QRCode.toBuffer(payload, { type: 'png', width: 512, margin: 0, errorCorrectionLevel: 'M' });
  const name = [student.first_name, student.middle_name, student.last_name].filter(Boolean).join(' ').replace(/\s+/g, ' ').trim();
  const section = [student.current_grade_level, student.sections?.section_name].filter(Boolean).join(' - ') || 'N/A';
  const birth = student.birth_date || 'N/A';
  const gender = student.gender || 'N/A';
  const displayId = student.stud_id;
  const safeId = displayId.replace(/[^a-zA-Z0-9_-]/g, '-');
  const pngName = `qr-${safeId}.png`;
  const htmlName = `qr-${safeId}.html`;
  const wrapper = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>QR Code - ${escapeHtml(displayId)}</title><style>body{margin:0;display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;background:#fff;font-family:Arial,sans-serif}img{width:320px;height:320px;display:block;image-rendering:pixelated}p{margin:10px 0 4px;font-size:13px;color:#374151;text-align:center}.id{font-size:15px;font-weight:bold;color:#111}</style></head><body><img src="data:image/png;base64,${png.toString('base64')}" alt="QR Code"><p class="id">${escapeHtml(displayId)}</p><p>${escapeHtml(name)}</p><p>${escapeHtml(section)}</p></body></html>`;
  const html = `<html><head><meta charset="UTF-8"></head><body style="font-family:Arial,sans-serif;color:#1f2937;line-height:1.5"><h2>Manual Attendance QR Code</h2><p>Hello ${escapeHtml(name || 'Student')},</p><p>Your QR code for Manual Attendance has been generated. Please keep this QR code and present it when facial recognition is unavailable.</p><p>Your QR code is attached as <strong>${escapeHtml(pngName)}</strong>. On mobile, tap the attachment to preview or download it.</p><table cellpadding="6" cellspacing="0"><tr><td><strong>Name</strong></td><td>${escapeHtml(name || 'N/A')}</td></tr><tr><td><strong>Student ID</strong></td><td>${escapeHtml(displayId)}</td></tr><tr><td><strong>Section</strong></td><td>${escapeHtml(section)}</td></tr><tr><td><strong>Birth Date</strong></td><td>${escapeHtml(birth)}</td></tr><tr><td><strong>Gender</strong></td><td>${escapeHtml(gender)}</td></tr></table><p>Generated by the Attendance Monitoring System.</p></body></html>`;
  const text = `Manual Attendance QR Code\r\n\r\nHello ${name || 'Student'},\r\nYour QR code for Manual Attendance has been generated.\r\nStudent ID: ${displayId}\r\nSection: ${section}\r\nBirth Date: ${birth}\r\nGender: ${gender}\r\n\r\nAttachment: ${htmlName}\r\nGenerated by the Attendance Monitoring System.\r\n`;
  return { to: student.email || '', subject: 'Your Manual Attendance QR Code', html, text,
    attachments: [{ filename: htmlName, content: wrapper, contentType: 'text/html' },
      { filename: pngName, content: png, contentType: 'image/png' }] };
}

export async function sendQrMail(mail: QrMail): Promise<void> {
  const address = process.env.GMAIL_ADDRESS?.trim() || '';
  const password = process.env.GMAIL_APP_PASSWORD?.trim() || '';
  if (!address || !password) throw new Error('SMTP is not configured');
  const smtp = nodemailer.createTransport({ host: 'smtp.gmail.com', port: 587, secure: false,
    requireTLS: true, auth: { user: address, pass: password }, connectionTimeout: 10000,
    greetingTimeout: 10000, socketTimeout: 20000 });
  await smtp.sendMail({ from: { name: 'ATTENDANCE MONITORING SYSTEM', address }, ...mail });
}
