<?php
declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');

function jsonExit(int $statusCode, array $payload): void {
    http_response_code($statusCode);
    echo json_encode($payload);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonExit(405, [
        'success' => false,
        'message' => 'Method not allowed. Use POST.'
    ]);
}

$rawBody = file_get_contents('php://input');
$data = json_decode($rawBody, true);

if (!is_array($data)) {
    jsonExit(400, [
        'success' => false,
        'message' => 'Invalid JSON body.'
    ]);
}

$clean = static function ($value): string {
    return trim((string)($value ?? ''));
};

// Updated to match K-10 data
$email = $clean($data['email'] ?? '');
$lrn = $clean($data['lrn'] ?? '');
$firstName = $clean($data['firstName'] ?? '');
$middleName = $clean($data['middleName'] ?? '');
$lastName = $clean($data['lastName'] ?? '');
$sectionInfo = $clean($data['sectionInfo'] ?? '');
$birthDate = $clean($data['birthDate'] ?? '');
$gender = ucfirst($clean($data['gender'] ?? ''));
$qrPayload = $clean($data['qrPayload'] ?? '');

if ($email === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
    jsonExit(422, [
        'success' => false,
        'message' => 'A valid student email is required.'
    ]);
}

if ($lrn === '') {
    jsonExit(422, [
        'success' => false,
        'message' => 'Student LRN is required.'
    ]);
}

$fullName = trim(preg_replace('/\s+/', ' ', implode(' ', array_filter([$firstName, $middleName, $lastName]))));
$displaySection = $sectionInfo !== '' ? $sectionInfo : 'N/A';
$displayBirthDate = $birthDate !== '' ? $birthDate : 'N/A';
$displayGender = $gender !== '' ? $gender : 'N/A';
$qrImageSize = '512x512';
$qrHtmlSize = '320px';

if ($qrPayload === '') {
    $qrPayload = "Smart Academic Management System QR\n"
        . "Name: " . ($fullName !== '' ? $fullName : 'N/A') . "\n"
        . "LRN: {$lrn}\n"
        . "Section: {$displaySection}\n"
        . "Birth Date: {$displayBirthDate}\n"
        . "Gender: {$displayGender}";
}

$qrImageUrl = 'https://api.qrserver.com/v1/create-qr-code/?size=' . rawurlencode($qrImageSize) . '&margin=0&format=png&data=' . rawurlencode($qrPayload);
$qrImageData = @file_get_contents($qrImageUrl);
$hasQrAttachment = is_string($qrImageData) && strlen($qrImageData) > 0;
$qrImageBase64 = $hasQrAttachment ? base64_encode($qrImageData) : '';
$safeLrn = preg_replace('/[^a-zA-Z0-9\-_]/', '-', $lrn);
$qrFileName = 'qr-' . $safeLrn . '.png';

$esc = static function (string $value): string {
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
};

$subject = 'Student Attendance QR Code';
$emailBody = '
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family:Arial,sans-serif;color:#1f2937;line-height:1.5;">
    <h2 style="margin:0 0 12px;">Student Attendance QR Code</h2>
    <p style="margin:0 0 14px;">Hello ' . $esc($fullName !== '' ? $fullName : 'Student') . ',</p>
    <p style="margin:0 0 14px;">Your QR code for event attendance and entry exit has been generated. Please keep this QR code and present it when facial recognition is unavailable.</p>

    <p style="margin:0 0 14px;">Your QR code is attached as <strong>' . $esc($qrFileName) . '</strong>. On mobile, tap the attachment to preview or download it.</p>

    <table cellpadding="6" cellspacing="0" style="border-collapse:collapse;margin:0 0 14px;">
        <tr><td><strong>Name</strong></td><td>' . $esc($fullName !== '' ? $fullName : 'N/A') . '</td></tr>
        <tr><td><strong>LRN</strong></td><td>' . $esc($lrn) . '</td></tr>
        <tr><td><strong>Grade & Section</strong></td><td>' . $esc($displaySection) . '</td></tr>
        <tr><td><strong>Birth Date</strong></td><td>' . $esc($displayBirthDate) . '</td></tr>
        <tr><td><strong>Gender</strong></td><td>' . $esc($displayGender) . '</td></tr>
    </table>

    <p style="margin:0;">Generated by Smart Academic Management System.</p>
</body>
</html>';

$configuredFrom = trim((string)ini_get('sendmail_from'));
if ($configuredFrom === '' || !filter_var($configuredFrom, FILTER_VALIDATE_EMAIL)) {
    $configuredFrom = 'no-reply@sams.local';
}

$mixedBoundary = 'mixed_' . md5((string)microtime(true));
$altBoundary = 'alt_' . md5((string)microtime(true) . '_alt');

$textBody = "Student Attendance QR Code\r\n\r\n"
    . "Hello " . ($fullName !== '' ? $fullName : 'Student') . ",\r\n\r\n"
    . "Your QR code for Attendance has been generated.\r\n"
    . "LRN: {$lrn}\r\n"
    . "Grade & Section: {$displaySection}\r\n"
    . "Birth Date: {$displayBirthDate}\r\n"
    . "Gender: {$displayGender}\r\n\r\n"
    . "Attachment: qr-{$safeLrn}.html\r\n";

$message = "--{$mixedBoundary}\r\n"
    . "Content-Type: multipart/alternative; boundary=\"{$altBoundary}\"\r\n\r\n"
    . "--{$altBoundary}\r\n"
    . "Content-Type: text/plain; charset=UTF-8\r\n"
    . "Content-Transfer-Encoding: 8bit\r\n\r\n"
    . $textBody . "\r\n\r\n"
    . "--{$altBoundary}\r\n"
    . "Content-Type: text/html; charset=UTF-8\r\n"
    . "Content-Transfer-Encoding: 8bit\r\n\r\n"
    . $emailBody . "\r\n\r\n"
    . "--{$altBoundary}--\r\n";

if ($hasQrAttachment) {
        $htmlFileName = 'qr-' . $safeLrn . '.html';
        $htmlAttachment = '<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>QR Code - ' . $esc($lrn) . '</title>
<style>
    body { margin: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; background: #fff; font-family: Arial, sans-serif; }
    img  { width: ' . $qrHtmlSize . '; height: ' . $qrHtmlSize . '; display: block; image-rendering: pixelated; }
    p    { margin: 10px 0 4px; font-size: 13px; color: #374151; text-align: center; }
    .id  { font-size: 15px; font-weight: bold; color: #111; }
</style>
</head>
<body>
    <img src="data:image/png;base64,' . $qrImageBase64 . '" alt="QR Code">

    <p class="id">' . $esc($lrn) . '</p>
    <p>' . $esc($fullName) . '</p>
    <p>' . $esc($displaySection) . '</p>
</body>
</html>';

    $message .= "\r\n--{$mixedBoundary}\r\n"
        . "Content-Type: text/html; name=\"{$htmlFileName}\"\r\n"
        . "Content-Transfer-Encoding: 8bit\r\n"
        . "Content-Disposition: attachment; filename=\"{$htmlFileName}\"\r\n\r\n"
        . $htmlAttachment . "\r\n";
}

$message .= "--{$mixedBoundary}--\r\n";

$headers = [
    'MIME-Version: 1.0',
    'From: Smart Academic Management System <' . $configuredFrom . '>',
    'Content-Type: multipart/mixed; boundary="' . $mixedBoundary . '"'
];

$mailWarning = '';
set_error_handler(static function (int $severity, string $message) use (&$mailWarning): bool {
    $mailWarning = $message;
    return true;
});

$sent = mail($email, $subject, $message, implode("\r\n", $headers));

restore_error_handler();

if (!$sent) {
    $lastError = error_get_last();
    $smtpHost = (string)ini_get('SMTP');
    $smtpPort = (string)ini_get('smtp_port');
    $sendmailPath = (string)ini_get('sendmail_path');

    $diagnostic = $mailWarning
        ?: (($lastError['message'] ?? '') ?: 'No PHP warning was captured from mail().');

    jsonExit(500, [
        'success' => false,
        'message' => 'Failed to send email. Check PHP mail/SMTP configuration.',
        'diagnostic' => $diagnostic,
        'smtp' => [
            'host' => $smtpHost,
            'port' => $smtpPort,
            'sendmail_path' => $sendmailPath,
        ]
    ]);
}

echo json_encode([
    'success' => true,
    'message' => $hasQrAttachment
        ? 'Student QR email sent successfully with PNG attachment.'
        : 'Student QR email sent successfully, but the PNG attachment could not be generated.'
]);