'use strict';
const TZ = 'Asia/Manila';
let events = [], charts = {}, summaryRows = [];

document.addEventListener('DOMContentLoaded', () => {
  if (!window.supabaseClient) return fail('The database connection is unavailable.');
  ['btnApplyTrends','trendEventType','btnExportExcel','btnExportPdf'].forEach(id => document.getElementById(id).addEventListener(id === 'trendEventType' ? 'change' : 'click', id === 'btnApplyTrends' ? load : id === 'trendEventType' ? eventOptions : id === 'btnExportExcel' ? excel : pdf));
  init();
});
async function init() {
  loading(true);
  try {
    const {data,error}=await supabaseClient.from('events').select('event_id,event_name,event_date,end_date,time_start,time_end,event_type,status').order('event_date',{ascending:true});
    if(error) throw error; events=data||[]; types(); eventOptions(); await load();
  } catch(e) { console.error('[Event trends] events',e); fail('Unable to load events. Please try again later.'); }
  finally { loading(false); }
}
function types() { const s=document.getElementById('trendEventType'); s.innerHTML='<option value="">All Event Types</option>'+[...new Set(events.map(x=>x.event_type).filter(Boolean))].sort().map(x=>`<option>${esc(x)}</option>`).join(''); }
function eventOptions() { const s=document.getElementById('trendEvent'), old=s.value, type=document.getElementById('trendEventType').value; const rows=events.filter(x=>!type||x.event_type===type); s.innerHTML='<option value="">All Events</option>'+rows.map(x=>`<option value="${esc(x.event_id)}">${esc(x.event_name||'Unnamed event')} (${esc(x.event_date||'No date')})</option>`).join(''); if(rows.some(x=>String(x.event_id)===old))s.value=old; }
function filteredEvents() { const from=val('trendDateFrom'),to=val('trendDateTo'),type=val('trendEventType'),id=val('trendEvent'); return events.filter(x=>(!from||x.event_date>=from)&&(!to||x.event_date<=to)&&(!type||x.event_type===type)&&(!id||String(x.event_id)===id)); }
async function load() {
  clear(); destroy(); const es=filteredEvents(); if(!es.length)return empty(); loading(true);
  try { const ids=es.map(x=>x.event_id), [attendance,participants]=await Promise.all([rows('event_attendance','attendance_id,event_id,student_id,time_in,time_out,remarks,created_at',ids),rows('event_participants','event_id,student_id',ids)]); const checked=attendance.filter(x=>x.time_in); if(!checked.length)return empty(); summaryRows=summary(es,attendance,participants); render(summaryRows,buckets(checked),new Set(checked.map(x=>String(x.student_id))).size); }
  catch(e) { console.error('[Event trends] data',e); fail('Unable to load attendance data. Please try again later.'); } finally {loading(false);}
}
async function rows(table,columns,ids) { const out=[]; for(let i=0;i<ids.length;i+=200){const {data,error}=await supabaseClient.from(table).select(columns).in('event_id',ids.slice(i,i+200));if(error)throw error;out.push(...(data||[]));}return out; }
function summary(es,att,parts) { return es.map(e=>{const a=att.filter(x=>x.event_id===e.event_id), inIds=new Set(a.filter(x=>x.time_in).map(x=>String(x.student_id))),outIds=new Set(a.filter(x=>x.time_out).map(x=>String(x.student_id))),roster=new Set(parts.filter(x=>x.event_id===e.event_id).map(x=>String(x.student_id))),late=new Set(a.filter(x=>x.time_in&&isLate(x,e)).map(x=>String(x.student_id)));return {name:e.event_name||'Unnamed event',date:e.event_date,check:inIds.size,out:outIds.size,registered:roster.size||null,rate:roster.size?inIds.size/roster.size*100:null,late:late.size};}); }
function buckets(rows) { const group=val('trendGrouping'), map=new Map(); rows.forEach(x=>{const day=manilaDay(x.time_in),key=group==='weekly'?week(day):group==='monthly'?day.slice(0,7):day;if(!map.has(key))map.set(key,new Set());map.get(key).add(String(x.student_id));}); return [...map].sort(([a],[b])=>a.localeCompare(b)).map(([label,ids])=>({label,count:ids.size})); }
function manilaDay(t) { const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(t)),g=k=>p.find(x=>x.type===k).value;return `${g('year')}-${g('month')}-${g('day')}`; }
function week(day) { let d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));let y=d.getUTCFullYear(),s=new Date(Date.UTC(y,0,1));return `${y}-W${String(Math.ceil((((d-s)/86400000)+1)/7)).padStart(2,'0')}`; }
function isLate(r,e) { if(!e.event_date||!e.time_start)return /late/i.test(r.remarks||'');const s=new Date(`${e.event_date}T${e.time_start}+08:00`);return new Date(r.time_in)>new Date(s.getTime()+900000); }
function render(s,trend,unique) { set('statTotalAttendance',s.reduce((n,x)=>n+x.check,0));set('statTotalEvents',s.length);set('statTotalParticipants',unique);set('statAverageAttendance',(s.reduce((n,x)=>n+x.check,0)/s.length).toFixed(1));document.getElementById('trendSubtitle').textContent=`${val('trendGrouping').replace(/^./,x=>x.toUpperCase())} Manila-local grouping; each student is counted once per period.`; chart('trend','attendanceTrendChart','line',trend.map(x=>x.label),[{label:'Unique Checked-In Students',data:trend.map(x=>x.count),borderColor:'#176aa4',backgroundColor:'rgba(47,143,206,.18)',fill:true,tension:.25}]);chart('by','attendanceByEventChart','bar',s.map(x=>x.name),[{label:'Unique Check-Ins',data:s.map(x=>x.check),backgroundColor:'rgba(47,143,206,.75)'}]);chart('io','checkInOutChart','bar',s.map(x=>x.name),[{label:'Unique Check-Ins',data:s.map(x=>x.check),backgroundColor:'rgba(16,185,129,.7)'},{label:'Unique Time-Outs',data:s.map(x=>x.out),backgroundColor:'rgba(47,143,206,.7)'}]);document.getElementById('eventTrendTableBody').innerHTML=s.map(x=>`<tr><td>${esc(x.name)}</td><td>${date(x.date)}</td><td>${x.check}</td><td>${x.out}</td><td>${x.registered??'—'}</td><td class="${x.rate==null?'rate-na':''}">${x.rate==null?'Not available':x.rate.toFixed(2)+'%'}</td><td>${x.late}</td></tr>`).join('');document.getElementById('trendResults').hidden=false;document.getElementById('btnExportExcel').disabled=false;document.getElementById('btnExportPdf').disabled=false; }
function chart(key,id,type,labels,datasets){charts[key]=new Chart(document.getElementById(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'top'}},scales:{y:{beginAtZero:true,ticks:{precision:0}},x:{ticks:{autoSkip:false,maxRotation:55}}}}});}
function destroy(){Object.values(charts).forEach(x=>x.destroy());charts={};} function val(id){return document.getElementById(id).value;} function set(id,x){document.getElementById(id).textContent=x;} function esc(x){const d=document.createElement('div');d.textContent=String(x??'');return d.innerHTML;} function date(x){return x?new Date(x+'T00:00:00').toLocaleDateString('en-PH',{month:'short',day:'numeric',year:'numeric'}):'—';}
function clear(){['trendError','trendEmpty','trendResults'].forEach(id=>document.getElementById(id).hidden=true);document.getElementById('btnExportExcel').disabled=true;document.getElementById('btnExportPdf').disabled=true;}function loading(x){document.getElementById('trendLoading').hidden=!x;}function empty(){clear();document.getElementById('trendEmpty').hidden=false;}function fail(m){clear();const e=document.getElementById('trendError');e.textContent=m;e.hidden=false;}
function data(){return summaryRows.map(x=>({'Event':x.name,'Event Date':x.date,'Unique Check-Ins':x.check,'Unique Time-Outs':x.out,'Registered Participants':x.registered??'','Participation Rate':x.rate==null?'':x.rate.toFixed(2)+'%','Late Check-Ins':x.late}));}function excel(){if(!summaryRows.length||!window.XLSX)return;const w=XLSX.utils.json_to_sheet(data()),b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,w,'Event Trends');XLSX.writeFile(b,'event_attendance_trends.xlsx');}function pdf(){if(!summaryRows.length||!window.jspdf)return;const {jsPDF}=window.jspdf,d=new jsPDF({orientation:'landscape'});d.text('Event Attendance Trends',14,16);d.autoTable({startY:22,head:[Object.keys(data()[0])],body:data().map(Object.values),styles:{fontSize:8},headStyles:{fillColor:[11,78,120]}});d.save('event_attendance_trends.pdf');}
